# environment variables
environment:
  nodejs_version: "6"
  access_token:
    secure: QFiSpRDUCJvizXjLbEIBNQd67Eyqf29w8ahmQFKL8JcReLKz/RGMWWpJMuN7+czx
# scripts that run after cloning repository
install:
  # install node 
  - ps: Install-Product node $Env:nodejs_version
  - npm install -g npm
  - npm install -g webpack  
  
# scripts to run before build
# Post-install test scripts.
test_script:
  # install node modules
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd TypeScript-Angular1-Adv
  - npm install
  # run webpack with production flag
  - webpack -p
  
artifacts:
  - path: TypeScript-Angular1-Adv/dist
# Don't actually build.
build: off
deploy_script:
  - cd..
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email joymon@gmail.com
  - git config --global user.name "joymon"
  - git subtree push --prefix TypeScript-Angular1-Adv/dist origin gh-pages
