# environment variables
environment:
  nodejs_version: "6"
  access_token:
    secure: YwffwDvba/ADlMJbtnOM7cKUqudcbYCt2K74HOtBvscwylmIMSRmrX2VKc+fuNjN
# scripts that run after cloning repository
install:
  # install node 
  - ps: Install-Product node $Env:nodejs_version
  - npm install -g npm
  - npm install -g webpack  
  
# scripts to run before build
# Post-install test scripts.
test_script:
  # install node modules
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd TypeScript-Angular1-Adv
  - npm install
  # run webpack with production flag
  - webpack -p
  
artifacts:
  - path: TypeScript-Angular1-Adv/dist
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - cd..
  - ps: Copy-Item TypeScript-Angular1-Adv\dist\* docs
  - git config --global user.email "joymon@gmail.com"
  - git config --global user.name "joymon"
  - git commit -- docs
  - git push origin master 
# Don't actually build.
build: off
